### ISSUE TITLE
Namen

### ISSUE THREAD

**Issue by lukruh** [telebotter/projekt47#10]
damit nicht alle helden peter heissen, waere vlt. ne db tabelle mit namen nice, kann ja einach nur flat ein string als eintrag haben und im generator waehlt man dann 4 zufaellige aus (vlt. sogar noch nen reroll button), die vorgeschlagen werden.. denke das ist schnell gemacht und man kann die tabelle dann ja easy erweitern..

**Comment by hendricokakiko** [comment]
namentabelle ist gepushed

**Comment by lukruh** [comment]
model ist erstellt und gepusht.. allerdings noch nicht im admin interface

**Comment by lukruh** [comment]
namen sind in die db eingetragen (script in management)
und im admin interface verlinkt.
