### ISSUE TITLE
inspect

### ISSUE THREAD

**Issue by lukruh** [telebotter/projekt47#12]
waere doch praktisch, wenn man spieler anschauen koennte zB
`/info` als zitat auf eine spieler nachricht, oder optional mit @username als argument. Eigene profilseite ohne argument.. Auf dem profil steht spaeter vlt. etwas statistik aber erstmal ne liste von helden die man anklicken kann und dann kommt die helden vorschau mit story + werte + aktionen.. (auf max nachrichtenlaenge achten).

Der Info text sollte auch erscheinen wenn man einen helden waehlt (statt direkt in den generator zu jumpen) mit einem `bearbeiten` butto der direkt zum namens state des convhandlers springt. (Ich find das game sollte man nicht aendern koennen.. dann muessen wir auch nciht aufpassen, dass werte und aktionen geloescht werden) 

- [x] Character info_text und info_stats methoden (char to text)
- [x] bot commands in commands.py
- [ ] links und/oder mentions abfragen statt from_user

**Comment by lukruh** [comment]
vlt. besser /char(s) weil info ja auch hilfe sein koennte? obwohl dafuer passt auch /hilfe xD ich lass es mal offen

**Comment by hendricokakiko** [comment]
/stats für charakterstats, /info für nen infotext zum char (story, optional), und /hilfe für den hilfe command

**Comment by hendricokakiko** [comment]
wie funktioniert das mit reply? finde die funktion klingt sehr geil in kombination mit /stats @argument

**Comment by lukruh** [comment]
meinst du auf die beantworteten nachrichten zuzugreifen? 

Wenn die Nachricht/Befehl, als antwort auf eine andere nachricht geschickt wird, ist eine referenz auf diese in `update.message.reply_to`

oder meinste den shortcut, als bot zu antworten? Der ist einfach `update.message.reply_text(text)` statt `bot.send_message(update.message.chat_id, text)` (oder so aehnlich)

wenn du den verlinkten user haben willst mit @username, dann ist der glaub ich in der message als entity.

fuer alles drei (und generell hilfreich)
https://python-telegram-bot.readthedocs.io/en/stable/telegram.message.html

**Comment by lukruh** [comment]
> /stats für charakterstats, /info für nen infotext zum char (story, optional), und /hilfe für den hilfe command

Jo find ich gut!

**Comment by hendricokakiko** [comment]
finde das update.message.reply_to nicht

**Comment by lukruh** [comment]
heisst auch reply_to_message sorry
https://python-telegram-bot.readthedocs.io/en/stable/telegram.message.html#telegram.Message.reply_to_message

**Comment by lukruh** [comment]
> /stats für charakterstats, /info für nen infotext zum char (story, optional), und /hilfe für den hilfe command

 am besten dann auch direkt die entsprechenden funktionen `stats_msg()` und `info_msg()` oder so in die models.Character klasse wuerd ich sagen.. dann kann man die immer direkt fuer jeden char benutzen.

**Comment by lukruh** [comment]
fuer einen selbst ists drin, fuer andere muss man nur `from_user`, durch entsprechende `reply_to_message.from_user` ersetzen, oder fuer @mentions als argument die enteties parsen. Da wir das ja scheinbar haeufiger brauchen waere vlt. ne funktion `utils.get_third_users(update, entities=True, quoted=True)` praktisch, die automatisch eine liste von usern zurueckgibt die in mentions und/oder zitaten gefunden wurden.

**Comment by lukruh** [comment]
mit /story kann man btw. story aendern.. oder im webinterface

**Comment by lukruh** [comment]
edit buttons (in privat chat, unter dem eigenen char) um direkt zum skill menu zu kommen?

**Comment by lukruh** [comment]
das mit den @mentions lasse ich erstmal weg, ist mir zu nervig die fall unterscheidungen zu machen.. vorallem weil snochmal nen unterschied ist ob der user nen username hat oder nicht ... ich mach erstmal einfach nachrichten zitat, das ist simple.. die get_third_user kann ja spaeter noch nen issue werden

**Comment by lukruh** [comment]
get_third_user returnd quoted telegram user (oder orig. author), wenn der telegram user nen bot ist, oder kein char hat oder so, wirds failen.. kein error handling an dieser stelle, aber das kann man dann wenn noetig ergaenzen denke ich.. generell um statt dem author den spieler der zitiert wird (falls) zu verwenden kann in jenen funktionen direkt am anfang:
```
tg_user = update.message.from_user
player = ut.get_p_user(tg_user)
```
durch 
```
tg_user = ut.get_third_user(update)
player = ut.get_p_user(tg_user)
```
ersetzt werden
