### ISSUE TITLE
False Counter for skillpoints

### ISSUE THREAD

**Issue by hendricokakiko** [telebotter/projekt47#14]
Spiel Medivial lässt sich bei den Skilpunkten von 5 hoch oder runterskillen. Mit zweimaligemdruck auf die minus taste kommt man zur 2. Die 3 wird übersprungen

**Comment by lukruh** [comment]
jo hast recht.. ist aber bei allen spielen so, nicht nur medival. dann ists warsch einfach nen tippfehler in der methode oder in der anzeige.

**Comment by lukruh** [comment]
funzt und committed
