### ISSUE TITLE
command list

### ISSUE THREAD

**Issue by lukruh** [telebotter/projekt47#15]
bei ein paar bots (und jetzt auch dem template) hab ich es so gemacht, dass ich die funktionen alle in einer liste sammel. Bei vielen befehlen spart das etwas code beim registireren (einfach loop ueber die liste) und man kann meta daten angeben, in die man zB kurzinfo oder beispiele schreiben kann um automatisch hilfe seiten und die vorgeschlagene bot liste zu generieren usw.. 
vorallem kann man dann einfach beliebig viele aliase auf einen befehl legen die alle das gleiche bedeuten. In code:
```
commands = []

def start(bot, update):
    ...
start.alias = ['start', 'los', 'go', 'hallo']
start.info = 'Dieser Befehl startet die Konversation mit dem Bot'
commands.append(start)


for c in commands:
    for a in c.alias:
        dispatcher.add_handler(CommandHandler(a, c))
```

kann ich das fuer den projekt47bot auch machen oder verwirrt dich das?

**Comment by hendricokakiko** [comment]
jetzt nach der tollen erklärung, nein es verwirrt mich nicht :)

**Comment by lukruh** [comment]
man kann sich dann auch ne funktion machen, die zB die botbefehle so ausgibt das man sie direkt copy pasten kann um sie botfather zu schicken.. falls man lazy ist

**Comment by lukruh** [comment]
datei ist erstellt, neue einfache commands schreib ich ab jetzt dort rein, die anderen zieh ich rueber wenn ich naechstes mal dran arbeite.. fuer eben schnell nen neuen command. muss man die telegrambot.py schon garnicht mehr anfassen :) funzt wunderbar, wenn wir das noch auf context statt argumente umstellen sparen wir da auchnoch ein paar zeilen
