### ISSUE TITLE
zurueck button von cm_action

### ISSUE THREAD

**Issue by lukruh** [telebotter/projekt47#18]
insbesondere bei geteilten skillpunkten aber auch wegen anforderungen etc.. kann man wenn man faehigkeiten sieht, sich schnell ueberlegen oh ne dann doch mehr von stat a oder weniger von b um die noch zu holen etc.. waere gut wenn die reihenfolge umgedreht wird, oder es (warsch einfacher) nen zurueck button gibt.

**Comment by hendricokakiko** [comment]
ja deutlich pro zurück button!

**Comment by lukruh** [comment]
🔙

**Comment by lukruh** [comment]
hab nen issue fuer die validierung gemcht, also pruefen ob vorraussetzungen erfuellt sind..
