### ISSUE TITLE
Bot Avatar

### ISSUE THREAD

**Issue by lukruh** [telebotter/projekt47#2]
Da muss aufjedenfall nen nices Bild her, für unser corporate design ;).. 
Ich hab die bisher immer mit transparentem hintergrund gehabt (ist vlt. auch nice das zu haben, als icon oder so). Aber wenn du mit farbigem hintergrund besser findest, ist mir auch recht, dann würd ich glaub ich die anderen bilder noch anpassen, das jeder bot ne eigene farbe hat.

**Comment by hendricokakiko** [comment]
ist mir wurst - ich stelle mir ein wirrwar an charakteren vor - nen zauberer, nen stormtrooper, nen drachen, und irgendwo leicht hervorgehoben der bot mit dem schurrbart :)

**Comment by lukruh** [comment]
hm wimmelbild ist mir glaub ich zu krass ich wuerd eher so 2-3 chars machen und den bot vorne in der mitte.. vlt. mit zauberhut schwert und sonnenbrille oder was sonst noch so alles rein kann.. augenklappe laserpistole xD

**Comment by hendricokakiko** [comment]
Ein mittelaltermagierbot (gandalflike) kämpft auf dem avatar gegen einen robobot (spacebot, was auch immer) mit laserpistole und schutzschild oder so... laserschwert...

**Comment by lukruh** [comment]
Ich wuenschte ich waere krasser grafiker xD
