### ISSUE TITLE
remove unused/unfinished chars

### ISSUE THREAD

**Issue by lukruh** [telebotter/projekt47#20]
da bei jedem start der generierung ein char erstellt wrid, waere es gut die irgendwie automatisch aufrauemen zu koennen wenigstens von zeit zu zeit.. management.py comes into mind.

**Comment by hendricokakiko** [comment]
vllt auch ne funktion um komplett alle charaktere aus der DB zu löschen...
oder alle doppelt benannten charaktere pro person pro addon...

**Comment by lukruh** [comment]
Warum sollte man alle Charaktere Lieschen wollen? Und ob zwei gleich heißen sollte dem Spieler überlassen bleiben da wuerd ich dann eher ne pro Spieler slfunktion also vom bot einbauen oder man verbietet doppelte namen schon von vornherein aber hab bisschen sorge die einfach iwann fuer alle zu löschen ohne Warnung.. Falls das unabsichtlich war weiß man ja auch nicht ob man den richtigen löscht.

**Comment by lukruh** [comment]
Also ich finde doppelte namen sind entweder erlaubt oder verboten aber nicht erlaubt koennen aber random gelöscht werden xD

**Comment by hendricokakiko** [comment]
alle würde man löschen wollen um die db vor einem alpha release einmal leer zu räumen

**Comment by lukruh** [comment]
dafuer kann man einfach die db loeschen aber pls mach das nicht,da sind schon zuviele sachen drin die ich gern behalten will.. kannst einfach nen addon loeschen im webinterface, ein grossteil der damit verknuepften sachen (aktionen, werte, chars etc) werden dann automatisch mit geloescht.. (siehe models.py fuer details)

**Comment by lukruh** [comment]
```
python manage.py cleanchars
```

steht auch in der projekt47 readme
