### ISSUE TITLE
Reccourcen

### ISSUE THREAD

**Issue by hendricokakiko** [telebotter/projekt47#22]
Reccourcen implementieren neben den stats und actions (basics und specials)

darunter fällt vor allem Leben (HP) als reccource (Mana, energie usw werden doch regelmäßig aufgeladen oder? wäre nervig das dauernd einstellen zu müssen oder sehr ich das falsch? hat ein zauberer pro session nur 100mana und kann damit zB 10 mittelschwere zauber wirken?)

reccourcen als standart auf 100 (%) legen. mit skillpunkten kann die reccource erweitert werden (10% je skillpunkt)

**Comment by lukruh** [comment]
Also ich wuerd glaub ich bot Funktionen schreiben um leben anzupassen ist ja nicht viel arbeit, vom Code her. Sie aber nicht benutzen sondern mir merken oder irgendwo notieren wieviel leben ich zB hab

**Comment by lukruh** [comment]
Aber faends nice wenns zmd theoretisch möglich waere ganz ohne Zettel zu spielen

**Comment by lukruh** [comment]
mir schwebt sowas wie `/res hp -1` vor wenn man ein dmg gekriegt hat. (Evt fuer hp was man ja vermutlich in fast allen addons hat, sogar noch nen shortcut `/hp -1` und/oder `/dmg 1`). Aber wenn man nur /res angibt kommt ne liste mit allen ressourcen und deren akuerzungen und evt. der aktuelle wert.

fuer die ressourcen `class Ressource` brauchen wir (pro addon) die werte (beispiele): 
default=100, scale=10, name=Lebenspunkte, abbr=LP, addon=Fantasy

und pro charakter `class CharRessource`: 
char=Peter, res=Leben, max=110, current=75

**Comment by lukruh** [comment]
ok habe noch einen scale faktor eingefuegt, allerdings ist noch kein skillen der werte moeglich (bisher 3 ressourcen alle default auf 100) ein bzw zwei neue befehle (mit / ohne args):

![image](https://user-images.githubusercontent.com/7965770/74493640-ee84ca00-4ed2-11ea-83ad-eceb3df85e83.png)

**Comment by lukruh** [comment]
ist drin
