### ISSUE TITLE
Botname aus setting auslesen

### ISSUE THREAD

**Issue by hendricokakiko** [telebotter/projekt47#23]
der name des verwendeten bots soltle aus der settings datei in telebotter, wo auch die tokens und anderer private stuff drinne steht ausgelesen werden, statt direkt im code zu stehen

**Comment by lukruh** [comment]
steht in `settings.PROJEKT47_BOT`. Muss in der lokalen settings.py entsprechend eingetragen sein.

**Comment by lukruh** [comment]
man koennte nat. mit settings.get(.. ,default) nen fallback auf den bot setzen, aber denke das passt man sowieso nie wieder an.. also close
