### ISSUE TITLE
Debug var

### ISSUE THREAD

**Issue by hendricokakiko** [telebotter/projekt47#24]
eine debugvariable einführen die wenn auf True das logging und zeug ändert?

**Comment by lukruh** [comment]
bin mir auch noch nicht so ganz sicher was das bringen und wie genau das gemacht werden soll. aber nur schonmal als info bis dahin:
in der settings.py gibt es eine DEBUG wenn die auf true ist werden von django mehr fehlermeldungen ausgegeben und vorallem werden im browser direkt alle variablen und fehler usw angezeigt wenn eine website nicht geladen wird.. das ist auf dauer natuerlich ein sicherheitsproblem (zmd auf dem server), aber waerend der entwicklung oft hilfreich.
in der settings.py unter LOGGING stehen bei den loggern/handerln level, wenn man zb debug nachrichten haben will, kann man dies level vom logger mit dem bot namen von INFO auf DEBUG setzen.

**Comment by lukruh** [comment]
vlt. reichts die logging manuell anzupassen und ansonsten es an die django settings zu koppeln.. debug abhaengige sachen im script kann man dann mit   `settings.DEBUG` pruefen.. ist halt projekt weit und nicht pro app/bot
