### ISSUE TITLE
Strings ändern

### ISSUE THREAD

**Issue by hendricokakiko** [telebotter/projekt47#25]
alle strings sollten nochmal gegengeprüft werden. besonders die proben strings müssen geändert werden:
immer summe(stats) anzeigen oder gesamte rechnung (und würfelergebnis)
emoji, ergebniss fett, rechnung kursiv rest normal
bisschen ausprobieren was schick aussieht

**Comment by lukruh** [comment]
evt in eine datei outsourcen? viele sachen zB button texte oder der text im menu beim skillen, stehen im code an 3 oder 4 stellen, nervig da was zu aendern und sieht komisch aus wenn mans iwo vergisst.. einfach ne `strings.py` oder `constants.py`?

**Comment by lukruh** [comment]
hab ne constants.py erstellt und sie in utils und im bot mit * importiert.. 
also ab jetzt alles in caps einfach direkt in constants dann kann mans eins zu eins in den anderen teilen benutzen.. ohne den code zu aendern

**Comment by hendricokakiko** [comment]
Hab da jetzt einiges geändert (vorallem bei der eigl probe) , man sieht jetzt was man gewürfelt hat (als summe) so sollten die regeln leichter ins blut übergehen, ich denke das issue kann geschlossen werden wobei strings zu ändern und fehler zu finden natürlich ein dauerissue bleibt
