### ISSUE TITLE
Regeln command

### ISSUE THREAD

**Issue by hendricokakiko** [telebotter/projekt47#26]
command der kurz und knapp die regeln erklärt. 

regel nr 1: der GM hat recht usw

**Comment by lukruh** [comment]
vlt. etwas unnoetig und overkill, aber man koennte die regeln auch als einzelnes textfeld in die db schreiben.. nur um sie dann vom webinterface aus aendern zu koennen.. dann haette man alles an einem platz xD

**Comment by lukruh** [comment]
/regeln /regel /rules /rule alles das gleiche
![image](https://user-images.githubusercontent.com/7965770/74459925-61b71d80-4e8c-11ea-82ec-e48b09abf2b2.png)
