### ISSUE TITLE
Fantasy Addon vorbereiten

### ISSUE THREAD

**Issue by hendricokakiko** [telebotter/projekt47#27]
das addon wird märchen fantasy: bibi blocksberg gegen den schweinebärmann - alles ist möglich

und gerne als backup: mittelalter (medival) ohne magie falls das erste in die hose geht

**Comment by lukruh** [comment]
Jo wir machen mittelalter so nebenbei immer wuerd ich sagen, fuer standard sachen und Fantasy extra fuer den abend passend zur geschichte dann..

**Comment by lukruh** [comment]
nice dass schon ein paar metacarten drin sind.. ich habe die ressourcen klasse erstellt und LP (Leben) MP (Mana) und EP (Energie) als ressourcen eingefuegt.. Dachte Leben reggen durch schlafen/ruhephase, mana durch kraeuter / traenke / je nach char passendes ritual (blutmagier opfern, geistliche beeten, naturmagier muessen einen bestimmten baum finden, dornroeschen muss 1000 jahre schlafen etc..) Energie (fuer koerperliche anstrengung) laedt man durch essen und trinken wieder auf.. bei sehr niedriger energie wird man schwaechlich schlaefrig hungrig oder muede.

Immer wenn man reggt macht man einmal W6 dazu.. wenn aktionen etwas verbrauchen stehts im text.

**Comment by lukruh** [comment]
ein paar basiswerte hab ich auch ergaenzt denke so ist schon nen gutes grundkit bin aber auch noch offen fuer weitere zB Karma oder Menschlichkeit oder was einem noch so einfaellt.

**Comment by lukruh** [comment]
zum testen angriff als nicht special hinzugefuegt..  Fehlen auf jedenfall noch einige..

**Comment by lukruh** [comment]
nur um schonmal nen anfang zu haben hab ich mal die mittelalter namen als fantasy default names kopiert.. kann man ja noch anpassen, aber schonmal besser als wenns immer leer ist

**Comment by lukruh** [comment]
magisches projektil und fortbewegung sollten special sein oder? haette jetzt alles magische als special gemacht, da normale leute ja nicht zwangslaeufig zaubern koennen.

**Comment by lukruh** [comment]
hab noch mut und ausdauer, denke jetzt haben wir schon ein gutes kit an basiswerten..
 und ein paar weitere standard aktionen hinzugefuegt, da geht aber noch einiges :)

**Comment by lukruh** [comment]
Kreaturen:

Wald:
Wichtel, Kobolde, Gnome, sehr grosse Kleintiere (Hasen, Kroeten, Insekten), Gorrilas, sprechende Eulen, boese Raben (Augen von Hexen), Hexen, Baeren, Woelfe, Druiden, Ents (Wandelnde Baeume), Erdelementare (selten), Schamanen, Naturzauberer

Berge:
Gnolle, Trolle, Oger, Riesen (selten), Drachen (selten), Ziegen, Zentauren, Steinelementare (selten),
Stiermenschen (Hochebenen), Wilde Barbaren in Camps, Untote, Totenbeschwoerer (selten, gejagt)

Suempfe:
Krokodile und alle Arten von Reptilien, riesigen Spinnen und Quallen, vieles uebertraegt gifte und krankheiten. Wuermer und Maden und Egel/Aale in feuchtem boden. Dinoartige greifvoegel, die sich die grossen spinnen und menschen holen.. krabben, bieten viel utensilien kraeuter und monster loot, allerdings gefaehrliche gegenden ohne viel zivilisation.. 

Kueste:
Delfine zum reiten (nicht gezaehmt aber verspielt), Schildkroeten zum reiten (sehr weise, aber fallen immer auf den trick mit der essens angel rein.. denken sie waeren erfolgreiche jaeger in dem sie geduldig genug das gemuese verfolgen, bis sie es schliesslich bekommen), Inseln kleine Raptoren, festland befestigt, aber inseln rechtsfreier raum / piratenkoenig, schiffe alle schwer bewaffnet, teilweise flug/see hybride mit zeppelin/luftballons. Salzwasser korkodile, seepferdchen koennen reden, seesterne kann man essen (mehrfach, wenn man sie gut pflegt wie tammagotschi, dann wachsen die zacken nach). Hoch giftige quallen in jeder groessenordnung, toeten auch waale. Minikraken die auch an land/ ueber wasser kommen und ueberall durch/hoch kommen.


Technologie und Gesellschaft:
Keine Industrialisierung, aber mechanische Hochkultur, krasse aparate, teilweise mit magischen oder uebernatuerlichen elementen. Die grosse alianz ist eine extrem tolerante hochkkultur, ueber verschiedene wesen hinweg, dessen wissen sich verschmolzen hat. Berufe sind entsprechend oft durch natuerliche vorteile belegt.. zB Greifen, die ballons koordinieren und in richtige winde ziehen fuer langstrecken fluege.. Es gibt ausgebaute strassen, karten, schienen systeme, oger, minotauren und riesen geben anschwung springen von karren zu karren wie autoscooter, betaetigen dreisienen. Kobolde fahren komplexere aparate nahezu mechanische roboter, die in der lage sind zu ernten, baeume zu faellen und andere koerperliche arbeit effizient zu verrichten..

**Comment by lukruh** [comment]
Es gibt keine direkte boese Seite, aber alle die sich nicht an den Codex halten werden aus er Allianz ausgeschlossen, zwar nicht direkt verfolgt, aber verstossen und nirgendwo gedultet, daher oft rueckzug in die hohen berge und suempfe, die fuer die zivilisation uninteressant ist.

**Comment by lukruh** [comment]
Magie:
prinzipiell sind die meisten wesen in der lage magie zu wirken oder zumindest zu erkennen, die wenigsten interessieren sich allerdings dafuer, da das wirken von magie von mitgliedern der grossen allianz sehr aufwendig ist. Zauber funktionieren nur, wenn sie selbst entwickelt wurden und die meisten zauber gibt es einfach schon, wodurch langes studieren der bibliotheken und kreativitaet noetig ist um eigene zauber zu erlernen. Stellt man sich einen Zauber vor, der warscheinlich schon von etlichen anderen wesen gewirkt wurde, verlaeuft er immer etwas anders als erwartet, es ist eine menge geduld und magie noetig um endlich voll kontrollierbare zauber zu wirken. Zauber die man vollstaendig kontrolliert, kann man sich in der grossen zitadelle der grossen allianz patentieren lassen, anderen mitgliedern ist es verboten deinen oder aehnliche zauber zu wirken. Es kommt gelegentlich vor, dass es zauberrivalen gibt, dass mehrere leute um die kontrolle eines sehr aehnlichen zaubers streiten.. dies kann durch kampf bis zum tod oder ein kompliziertes ritual magischer verbindung aufgehoben werden.

**Comment by lukruh** [comment]
Die meisten probleme werden geloest durch Kraft (davon gibt es reichlich in einigen wesen), intelligenz (list und sehr effektive mechanik), geschick (im kampf eine alternative zur kraft, im alltag erspart es hier und dort manches werkzeug), magie (da magier in der regel eher wenig und nur sehr spezielle zauber koennen, sind einige von ihnen sehr gefragt, die meisten jedoch arbeitslos)

**Comment by lukruh** [comment]
Ideen zu spielbaren Wesen (beispielchars/inspirationen):

* Minotauren Bergbauer. Stark und Geschickt, kann mit Haemmern und Aexten umgehen, kann (Schienen)fahrzeuge lenken wie ein gott, da dies sein jahrelanges hobby und sein job war, ist aber auch zufuss schnell. Kennt sich in gebirgen aus, fuerchtet weder einsamkeit noch kaelte, geniesst aber auch die gesellschaft. Ein liebeswertes Muskeldings, dass nicht ganz so doof ist wie manche es ihm unterstellen.

* Robognom. Sieht auf den ersten blick aus wie ein grosser staemmiger Mensch, schaut man genauer hin, sieht man aber die zahnraeder und trichter in die ein kleiner gruener gnom dessen lange nase mal aus dem aermel und mal aus dem kragen ragt, dauernd oel nachkippt. Solange der roboter funktioniert, was oft nicht der fall ist, kann der gnom vieles durch intelligente konstruktionen umgehen, wofuer andere hart anpacken muessten.

* Urdruide. Warscheinlich das aelteste Menschenartige lebewesen, dass es ueberhaupt gibt. Gelassener als eine alte Eiche, mindestens genaus knochig, aber definitiv von mehr moos ueberwachsen. Die letzten hundert jahre schlief er meist mit den Bauemen im Wald. Seit dem 2 monatigen Nickerchen, aus dem er von einer Axt im Bein geweckt wurde, weil der Foerster ihn fuer Gestruepp hielt humpelt er. Relativ resistent gegen natuerliche einfluesse: gifte/krankheiten/temperatur/luft. Seine Magie ist rein naturverbunden, weil er noch aus so alter zeit kam waren die klassichen zauber noch offen.. mit tieren sprechen, oder sich sogar verwandeln. schlaeft er ein sieht er nach 1-2 stunden aus wie gebuesch.. 

* Hochstapler: Ein hochrangiger Adeliger, angesehener Buerger und konservativer Politiker, der von Steuern lebt und eine aktentasche voll offiziell beglaubigter Dokumente, mit etlichen unterschriften und siegeln.. Wer genug ansehen hat und die richtigen Leute kennt, kann viel auf dem legalen weg erreichen ohne sich die finger schmutzig zu machen.. Was die wenigsten wissen, ist dass seine Fassade frei erfunden und Zweckdienlich ist. Eigentlich ein Pirat dem das Rauben zu anstrengend und gefaehrlich geworden ist. Gewissen hat er keins. Kommt es zum Kampf laesst er kaempfen.. wenn es garnicht anders geht ist kein Trick zu dreckig um sich einen kleinen Vorteil zu verschaffen. Je weiter weg der Gegner desto besser.

**Comment by lukruh** [comment]
sollte als basis reichen um darauf aufbauend abenteuer zu gestalten.. kann ja noch mehr dazukommen ich lads demnaechst auf der website hoch
