### ISSUE TITLE
environment needs to be tested

### ISSUE THREAD

**Issue by lukruh** [telebotter/projekt47#3]
Ich find den workflow über den server manchmal etwas anstrengend (git machts etwas leichter) aber tortzdem bin ich immer über ssh drin um zumindest nach einer änderung den webserver neu zu starten.. 
Evt. wärs ne überlegung wert, ne lokale django installation zu haben um dort ohne umweg testen zu können.. aber vlt. macht das auch mehr arbeit, als einfach direkt auf dem remote zu arbeiten.

**Comment by hendricokakiko** [comment]
ja, wir brauchen ganz ganz dringend ein test enviroment! vor allem zu anfang! vielleicht ist es sogar besser erst die spiellogik zu schreiben (in reinem python) und anschließend die telegram ui drüber zulegen

**Comment by lukruh** [comment]
was gegen die testumgebung spricht, ist das du dich dann mit git rumschlagen musst ;) wenn du direkt auf dem server arbeitest, kannste halt einfach die dateien bearbeiten.. 
also das spiel erst als kommandozeilen tool basteln?

**Comment by lukruh** [comment]
Ich hab über ftp plugin, einfach immer direkt die projekte auf dem server im lokalen editor auf.. sobald ich speicher schreibt er das dann auf dem server.. 
aber hast trotzdem recht ne testumgebung wäre schon nice.. ich versuch schonmal die server env zu exportieren, dass man die gleichen biblioteken etc. in der lokalen env installieren kann. Weiß nur noch nicht genau wie man das mit der DB machen soll.. vlt. einfach ne lokale sqlite datei, die nicht mit dem server synchronisiert ist.

**Comment by lukruh** [comment]
setup zum lokalen testen erstellt..
siehe `installation.md`... 
wenns soweit funzt > close

**Comment by lukruh** [comment]
moved to telebotter/telebotter/INSTALL.md

**Comment by hendricokakiko** [comment]
ist es getestet? kann geclosed werden?

**Comment by lukruh** [comment]
Jup
