### ISSUE TITLE
Probe um x erschweren oder erleichtern

### ISSUE THREAD

**Issue by hendricokakiko** [telebotter/projekt47#30]
Funktion ist wichtig

**Comment by hendricokakiko** [comment]
elif data[0] == 'extendprobekbd':
        logger.warning('probe keyboard extend')
        #msg_text = msg.text
        msg_kbd = msg.reply_markup
        btns = msg_kbd.inline_keyboard
        if len(btns) > 1: # collapse
            log('collapse probe keyboard')
            msg_kbd = InlineKeyboardMarkup([btns[0]])
        else:
            log('expand probe keyboard')
            roll_btn = btns[0][0]
            # get probe details from first button
            cb_data = roll_btn.callback_data.split(',')
            row_plus = []
            row_minus = []
            for i in range(1,5):
                cb_data[3] = str(i)
                row_plus.append(InlineKeyboardButton(
                        '{:+d}'.format(i), callback_data=','.join(cb_data)))
                cb_data[3] = str(-i)
                row_minus.append(InlineKeyboardButton(
                        '{:+d}'.format(-i), callback_data=','.join(cb_data)))
            btns.append(row_plus)
            btns.append(row_minus)
            msg_kbd(btns)
        # msg.edit_text(msg.text, reply_markup=msg_kbd)  # not woking with imsg
        bot.edit_message_reply_markup(msg_kbd)


hab nicht verstanden wie ich das umbauen kann... das normale btns = [[a,b,c]] replyMarkup(btns) hat bei mir nicht funktioniert

**Comment by lukruh** [comment]
Das muss InlineKeyboardMarkup(btns) heissen und a b c muessen InlineButtons sein, dann sollte es funktionieren.
Das problem an der funktion war, dass man text von inline nachrichten (via @botname) nicht bearbeiten, sondern nur neu schreiben kann.. d.h. die info welche probe gemacht werden soll muss im expand button stecken, damit die anderen buttons entsprechend fuer die richtige probe generiert werden koennen... (action_id)

**Comment by lukruh** [comment]
habs jetzt einfach so gemacht, dass der expand button die gleichen daten uebergibt wie der wuerfelbutton (nur 'ext' statt den wert fuer den malus also 0) dann kann man neue buttons generieren und einfach die callback daten kopieren, wobei nur der letzte wert durch den malus ersetzt wird.. so muss man weder das keyboard noch die nachricht kennen, um die zusatz buttons anzuzeigen.. denke das ist relativ gut geloest so, einziger nachteil, man kann es nicht wieder einklappen.. aber who cares (normal wuerfeln button ist ja trotzdem noch drin)
