### ISSUE TITLE
Aktiven Charakter anzeigen

### ISSUE THREAD

**Issue by hendricokakiko** [telebotter/projekt47#31]
Der aktivierte char sollte im /cm menü mit *Name* eingetüdelt sein um schnell mal eben sehen zu können welcher char aktiv ist

**Comment by hendricokakiko** [comment]
vllt ein minor issue von #17

**Comment by lukruh** [comment]
oder im text stehen und garnicht mehr in der liste? 
ah ne wenn man auch bearbeiten soll ist schon gut wenn er schon in der liste ist..

**Comment by lukruh** [comment]
![image](https://user-images.githubusercontent.com/7965770/74456601-5f05f980-4e87-11ea-8cc6-5ec3f6c5d0bb.png)
sowat?

**Comment by lukruh** [comment]
hab jetzt in caps und eckige klammern.. kannst ja die zeile anpassen wenn du lieber sternchen oder emojis haettest

**Comment by lukruh** [comment]
👉👈☑️ die gibts sonst auch noch 

find so eig. nicht schlecht
![image](https://user-images.githubusercontent.com/7965770/74456919-cd4abc00-4e87-11ea-8c3d-6b3f9f58a750.png)

ich close mal kannste aendern wie du willst
