### ISSUE TITLE
stats actions validation

### ISSUE THREAD

**Issue by lukruh** [telebotter/projekt47#34]
wir muessen eine funktion einfuegen, die prueft ob man fuer die aktuellen aktionen genuegen stats hat und skillen entweder fehlschlagen lassen, oder vlt. besser (dann muss man die aktionen nicht loeschen) das nicht moedliche aktionen automatisch geloescht werden.
Auch einmal sicherstellen, dass nur moegliche aktionen angezeigt werden

**Comment by hendricokakiko** [comment]
von mir aus auch: du kannst die spezalaktion skillen, kannst dann wieder die basiswerte ändern, aber wenn du die probe auf spezalaktion ausführen willst kommt die fehlermeldung 'nicht genug kraft' oder so

**Comment by lukruh** [comment]
joah koennte man auch dort einbauen, aber dann muss man immer im hinterkopf haben, das chars ungueltig sein koennen.. waere nicer es von vornherein zu vermeiden bzw. vlt. sogar beides, dass man es nicht lernen kann, aber falls mans aus irgendeinem grund doch gelernt hat, bekommt man die fehlermeldung.. bzw. ne warnung find ich eig. angebrachter.. also das die probe stattfindet, aber die anmerkung dort steht

**Comment by lukruh** [comment]
zumindest werden die proben jetzt schonmal gefiltert, ob gelernt oder nicht..

**Comment by lukruh** [comment]
sind noch durch den conversation handler bedingt kleine details die fehlen.. zB werden aktionen die man gelernt hat in der nachricht erst angezeigt nachdem man eine neue aktion gedrueckt hat.. das sind verschiedene states deines conversation handlers, aber die nachricht sieht immer gleich aus.. kb den code immer mehrfach zu schreiben xD denke dass wir uns da iwann sowieso noch was anderes ueberlegen muessen mit den ganzen callbacks vs conversations

however, wenn man ueber 4 skliled werden alle gelernten spezialaktionen die das talent brauchen automatisch entfernt und man bekommt die skillpunkte wieder (mit popup hinweis), denke das reicht erstmal
