### ISSUE TITLE
basiswert proben

### ISSUE THREAD

**Issue by lukruh** [telebotter/projekt47#35]
am besten die basiswerte direkt mit in die liste aufnehmen?

**Comment by hendricokakiko** [comment]
ja!

**Comment by lukruh** [comment]
ok, hab mal ne funktion in die utils geschoben, die diese inlinequeryresults generiert, das hat sich dann doch ein paar mal wiederholt und ist viel weil man schon alle moeglichen nachrichten mit allen buttons generieren muss.. wenn sie nur vorgeschlagen werden.. Die funktion sollte ebenfalls fuer basiswerte funktionieren.. 
die vorgeschlagenen aktionen fuer proben, habe ich schonmal gefiltert, nurnoch basisaktionen aus dem addon + spez aktionen des chars werden angezeigt.. dafuer aber ich logische db abfragen genuzt (alle actions mit addon=a und entweder special=false oder chars__in=char)
https://docs.djangoproject.com/en/dev/topics/db/queries/#complex-lookups-with-q-objects
und generell zu den abfragen:
https://docs.djangoproject.com/en/2.2/ref/models/querysets/

die probe() hab ich auch so angepasst, dass sie zmd theoretisch statt action auch einfach nen stat als argument verwerten kann.. jetzt muss nurnoch der callback button (mit dem wuerfel drauf) die stats an die proben funktion uebergeben..

**Comment by lukruh** [comment]
funzt.. jeder char bekommt bei der generierung alle stats aus dem addon, die funktion fragt einfach alle stats vom addon ab und durchsucht nicht die stats vom charakter.. sprich wenn man die addons nach erstellung der chars aendert, werden proben zu den neuen stats fehlschlagen.. da muss man sich evt. generell ein paar complexere sachen fuer die DB ueberlegen, was bestimmte bedingungen schon auf db level forciert.. zb jeder char MUSS jeden stat genau einmal haben
