### ISSUE TITLE
proben fuer mehrere durch inlinequery

### ISSUE THREAD

**Issue by lukruh** [telebotter/projekt47#7]
👨‍💻 Lukas, [27.01.20 18:00]
jo also ich würd auch sagen, entweder multiprobe und alle können drücken oder nur der prober.. der kompromiss ergibt wenig sinn, dass ein beliebiger drücken kann und die probe dann "verbraucht" ist.

Hendrik Freiheit, [27.01.20 18:01]
Finde alle können drücken

👨‍💻 Lukas, [27.01.20 18:01]
die frage ist halt ob die helden id beim @command gesetzt wird und dann im button steht oder ob der button nur die aktion enthält und die heldenid durchs drücken gelesen wird

👨‍💻 Lukas, [27.01.20 18:01]
kk denke auch.. ist auch glaub ich sorum einfacher es später zu limitieren, als andersrum zu erweitern

👨‍💻 Lukas, [27.01.20 18:02]
kurz afkaffee.. 
btw. inlinequery scheint tatsächlich nur mit webhook zu gehen, oder ich hatte lokal grad nen anderen fehler übersehen..

Hendrik Freiheit, [27.01.20 18:04]
Afk einkaufen

👨‍💻 Lukas, [27.01.20 18:11]
ooh da kommt mir noch eine idee.. wenn wir das mit dem würfeln als extra step machen kann man da auch die erschwernis mit einbauen.. 

msg
Klettern Probe [🧠💪]:

btns:
[-2][-1] [🎲] [+1][+2]

Hendrik Freiheit, [27.01.20 18:12]
Ja super!

👨‍💻 Lukas, [27.01.20 18:13]
oder halt
[🎲] [ ... ]
 
und wenn man auf ... drückt kommt
+4 +3 +2 +1
-4 -3 -2 -1

👨‍💻 Lukas, [27.01.20 18:13]
das find ich glaub ich am besten, dann hat man das schonmal aus dem queryhandler raus, und spart sich die logik wann welche proben angezeigt werden :)

**Comment by lukruh** [comment]
👨‍💻 Lukas, [28.01.20 17:20]
boah diese inlinequeries sind schon echt sperrig.. wenn die nachricht beim abschicken in die db soll muss jedesmal wenn ein buchstabe der in der inlinequery eingegeben (oder geloescht) wird, jeder moegliche Vorschlag ein neues db objekt erstellen.. das waere bei 25 mgl aktionen und 3 eingegeben buchstagen schon etwa 50 db eintraege ohne dass ueberhaupt irgendwas gepostet wurde..

👨‍💻 Lukas, [28.01.20 17:21]
das ist das problem, was ich meinte als ich gesagt habt die inline queries muessen statisch programmiert werden.. also alles was auf den knopfdruck folgen koennte muss schon ausgefuehrt werden, bevor der vorschlag angezeigt wird..

👨‍💻 Lukas, [28.01.20 17:25]
weil man ja vorher nicht weiss welchen vorschlag der nutzer auswaehlt und man kein feedback mehr bekommt, bis der wuerfel button gedrueckt wird.. einzige moeglichkeit die ich sehe ist eine referenz zur nachricht in die callbackdaten vom button zu packen und alle infos die gebraucht werden um das objekt zu erstellen (aktion id, proben id, imsg id, malus) und dann werden die nachrichten im CallbackHandler *der bei jedem button druck getriggert wird) geloggt statt im InlineQueryHandler (der bei jeder eingabe in die @ zeile getriggert wird)..

👨‍💻 Lukas, [28.01.20 17:26]
einziges feedback waere halt die nachricht selbst, das funktioniert aber nur wenn der bot in der gruppe ist, was ja iwie ne unnoetige vorraussetzung ist.

👨‍💻 Lukas, [28.01.20 17:34]
ooh es gibt doch ne moeglichkeit den user klick zu tracken... man kann dadurch nen update vom tg server triggern...

👨‍💻 Lukas, [28.01.20 17:34]
[ Photo ]

👨‍💻 Lukas, [28.01.20 17:35]
im telegramchat wurde mir/uns allerdings von diesem ansatz abgeraten, da inlinequeries nicht dafuer gemacht sind und das bei vielen nutzern eine menge spam verursachen kann.. aber ich denke nicht, das unsere userzahl jemals 100 ueberschreiten wird oder?

👨‍💻 Lukas, [28.01.20 17:51]
ok in dem update, dass dem bot dann geschickt wird, wenn ein user einen button anklickt, steht leider auch keine referenz auf die nachricht, sondern nur die id der nachricht..

👨‍💻 Lukas, [28.01.20 17:55]
das koennte man aber hacken, indem man die ID des helden und der aktion in die ID des Vorschlags einarbeitet und dann sobald ein Vorschlag gewaehlt wurde, bekommt der bot die ID und damit den helden und die aktion die beim werfen geprueft werden soll..

ODER

wir scheissen erstmal auf mehrfach klickbare nachrichten, packen aktion (ohne held) ins button callback und mit einem klick wird die probe ausgefuehrt (vom helden des klickers) und das ergebnis in der nachricht gezeigt feddisch. 
wenn jemand anderes auf den button klickt, ist das halt so. Fuer multiproben, koennen wir uns dann immernoch spaeter was ueberlegen

**Comment by hendricokakiko** [comment]
denke fast das issue kann geschlossen werden. finde es sehr leicht im aktuellen bot eine probe durchzuführen. up to you

**Comment by lukruh** [comment]
jo denke auch ist nicht notwendig, bzw nen einfacher befehl reicht.. kann ja sonst wieder aufgemacht werden
