### ISSUE TITLE
add skillpunkte

### ISSUE THREAD

**Issue by lukruh** [telebotter/projekt47#9]
Hendrik Freiheit, [29.01.20 15:08]
Ja pro game, später noch ein hardcode /addskillpunkt oder so um weiter zu skillen nach nem raid/session

**Comment by lukruh** [comment]
hatte mir sowas gedacht wie `/addxp @player1 @player2 @player3 2` um als gm 3 spielern je 2 skillpunkte zu geben.. problem dabei ist, dass man nur user mentionen kann, die auch in der konversation sind.. ich kann also dich zb nicht linken wenn ich direkt dem bot schreibe, und befehle immer in ne gruppe mit bot + spieler schreiben zu muessen (ausserdem den spieler dabei benachrichtigen) finde ich sehr unbefriedigend.. 

alternativ koennte man nachrichten von usern forwarden oder zitieren find ich aber noch umstaendlicher und es wuerde nur fuer einen gehen. Dann waere da noch der charakter name dem man ja xp geben koennte, dieser ist aber sicherlich nicht einzigartig.. Die einzig eindeutige zuordnung waere die charakter ID aus der DB aber die einzugeben kommt mir auch extrem scheisse vor.. `/addxp 192 181 211 241 2` ist finde ich ziemlich beschissen.. 

Das koennte schon der erste vorteil sein, den man haette, wenn man die spieler einer session mit einem char beitreten lassen wuerde. Dann koennte man ganz einfach allen session teilnehmern xp geben.

Ich lass das erstmal so stehen, vlt. hast du ja noch ne idee oder ich die tage, bis dahin kann man dann erstmal nur sich selbst xp geben oder halt ueber die DB.

**Comment by lukruh** [comment]
Ha, doch noch ne idee.. das ist zwar uebelst der umweg, aber vlt. auch ganz nice.. als GM/Admin/Jeder kann man xp guthaben verschicken (zB inline command oder normaler command) dann kommt eine nachricht "Es liegen <X> Erfahrungspunkte bereit." mit nem nehmen button. Der button kann dann optional einmal gedrueckt werden und die nachricht verschwindet, oder kann pro spieler einmal gedrueckt werden und wer schon war kriegt beim zweiten druecken einfach nen fehler.. 

das ist zwar etwas um die ecke, aber ich find die idee eig. sehr witzig. Bei den proben ist es ja auch so, dass man die probe postet und dann erst wuerfelt..

**Comment by lukruh** [comment]
sowas kann man dann auch in der halbzeit zb mal droppen

**Comment by lukruh** [comment]
`/addskillpoints`, `/xp`, `/skillpunkte` und so weiter geben dem spieler jetzt ein erfahrungswert. Wenn das erste argument ein integer ist, werden soviel punkte gegeben (oder genommen kann auch negativ sein). Geht logsicher weise nur mit aktiviertem char.

**Comment by lukruh** [comment]
`@projekt47bot xp 4` Bietet jetzt Einfachloot (verschwindet nach klick) oder gruppen loot (passiert noch nichts). 

Mittelfristig brauchen wir eine vernuenftige validierung fuer die klicks, um zu verhindern, dass ein user aus der gruppe mehrfach klickt.. haelt man die msg bzw. spieler id in einer variable, koennte ein spieler nach bot neustart beispielsweise erneut klicken. Crasht der bot genau nach dem klick koennten spieler unendlich oft klicken wenn der button nicht verschwindet.. 

also 
1) entweder, man schreibt die user ids als liste in den button (button callback data wird ja auf tg server gespeichert und ist da solange der button geht), das waere aber in der laenge limitiert, oder 
2) man macht einen random code rein, der in einer bot variable gehalten wird und wenn der bot neustartet, oder nach einer gewissen zeit verfaellt der code. Oder 
3) jede gepostete XPNachricht bekommt nen db eintrag mit id und man kann nachpruefen ob und wer wann was rausgenommen hat.. kommt mir abe rauch etwas unnoetig vor dafuer jedesmal die DB zu durchforsten wenn inen otto 20mal auf den link klickt..

PS Ich gehe natuerlich davon aus, dass man sich wenn alles fertig ist nichtmehr einfach selbst xp geben kann, sondern nurnoch gmuser das verteilen koennen.. oder soll man das eher komplett frei machen? Eig. hatten wir ja eh mal gesagt, cheat schutz ist eig. egal weil wer bei dem game betruegen wlil.. naja der kann eh machen was er will xD

**Comment by lukruh** [comment]
btw. dass man vorher nicht sieht wieviele drin sind (auc negativ ist moeglich) hab ich erstmal absichtlich gemacht.. find ich witzig und so kann man als meister trolle trollen..

**Comment by hendricokakiko** [comment]
wow! denke es sollte nicht da stehen wieviele skillpunkte es gibt.
ABER: was passiert bei negativen skillpunkten? werden meine stats tatsächlich dadurch verändert? denke nein. wie lösen wir das?

**Comment by hendricokakiko** [comment]
denke ausserdem auch das die skillpunkte auch bis 6 gehen sollten. das bedeutet wenn du eine eigenschaft auf 6 hast failst du immer bei der einzelprobe darauf. du bist zu schwach, also kannst du keinen stein hochheben. ist der stein leichter gibt dir der gm -3 auf die probe und du kannst es trozdem schaffen
was hälst du davon?

**Comment by lukruh** [comment]
Weiss nicht genau was du meinst.. Also was die skill Punkte mit der Probe zu tun haben. Die basiswerte gehen ja zur Zeit von 1-5 da man ueber den Wert kommen soll und ich es gut finde wenn man imner die chance hat es zu schaffen oder zu platzen. Wenn man ueber ne 6 kommen muss braucht man ja mit nem w6 nicht zu würfeln.

**Comment by hendricokakiko** [comment]
aber es zeugt auch schon von interesse es auszureizen wenn du etwas absichtlich auf 6 herrunter skillst.
ansonsten kann auch ein unerfahrener mit viel glück eine oberkrass pyroschlag probe (magie, kraft) bestehen obwohl er magie auf 5 geskillt hat. (kann er sonst auch, aber nur dadurch dass er magie durch kraft ausgleicht)

**Comment by hendricokakiko** [comment]
das andere ist: du kannst negative skillpunkte erhalten - sie änderen aber deine geskillten werte erstmal nicht. soll das so bleiben? sollen bei negativsillungen direkt random irgendwo werte abgezogen werden? oder auch spezifisch auf den gm befehl? zB /xp -2 @player Magie

**Comment by lukruh** [comment]
> ansonsten kann auch ein unerfahrener mit viel glück eine oberkrass pyroschlag probe (magie, kraft) bestehen obwohl er magie auf 5 geskillt hat. (kann er sonst auch, aber nur dadurch dass er magie durch kraft ausgleicht)

naja da pyroblast vlt. nicht das ist, was jeder letzte otto kann, dachte ich vermeidet man es indem man es als spezialfaehigkeit ja ueberhaupt nur lernen kann wenn man besser als ne 4 auf den werten ist..

das mit den negativen skillwerten hab ich jetzt erstmal so gelassen, finde random werte abziehen nicht gut, wuerd es eher als kredit sehen, dass man wenn man zB im spiel mist macht -1 bekommt und am ende kriegen alle 2 oder 3 punkte und der der mist gemacht hat dadurch netto 1 weniger. Hatte es nicht so gedacht, dass das ein richtiger usecase sein soll negative xp zu haben..  aber hab da auch keine feste meinung zu.. wichtig ist mir nur, dass man generell xp abziehen kann wenn man falsch gegeben hat oder halt als strafe

**Comment by hendricokakiko** [comment]
und wir sollten uns überlegen wenn jemand die xp annimt (auf den button klickt), dass dann auch eine nachricht aufpoppt die zeigt wie viele xp er bekommen hat

**Comment by lukruh** [comment]
![image](https://user-images.githubusercontent.com/7965770/74339297-1a556200-4da4-11ea-9e96-c4f016179bd5.png)
ist doch

**Comment by lukruh** [comment]
die strings koennen halt alle noch ordentlich gemacht werden und/oder mit smilies versehen.. Darauf hatte ich bisher kein bock xD

**Comment by lukruh** [comment]
/xp geht jetzt auch an zitierte spieler
